name: delete-preview

on:
  workflow_call:

jobs:
  delete:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Delete preview files
        run: |
          rm -rf _preview/${{ github.event.pull_request.number }}
      - name: Commit the changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: Delete preview for pull request \#${{ github.event.pull_request.number }}